// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0URG1EhIPTHD2KoOYsq4V_AkqQN9h1gM',
    appId: '1:707723557463:web:8535b1d43ed859f3b70112',
    messagingSenderId: '707723557463',
    projectId: 'langapp-81b4d',
    authDomain: 'langapp-81b4d.firebaseapp.com',
    storageBucket: 'langapp-81b4d.appspot.com',
    measurementId: 'G-WECM5GJ1DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvju_3RYJcEuv6D8X6JhhKx4OxCGg-QT4',
    appId: '1:707723557463:android:8335b3cac97c6397b70112',
    messagingSenderId: '707723557463',
    projectId: 'langapp-81b4d',
    storageBucket: 'langapp-81b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-s-SfWOvB0zPfnZZ8xPqxUYUyxAFpKw',
    appId: '1:707723557463:ios:cf14ec0a42b1a611b70112',
    messagingSenderId: '707723557463',
    projectId: 'langapp-81b4d',
    storageBucket: 'langapp-81b4d.appspot.com',
    iosClientId: '707723557463-knk34jmgqnv85i2ajq5jlsof3bkktf3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.langapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-s-SfWOvB0zPfnZZ8xPqxUYUyxAFpKw',
    appId: '1:707723557463:ios:cf14ec0a42b1a611b70112',
    messagingSenderId: '707723557463',
    projectId: 'langapp-81b4d',
    storageBucket: 'langapp-81b4d.appspot.com',
    iosClientId: '707723557463-knk34jmgqnv85i2ajq5jlsof3bkktf3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.langapp',
  );
}
